---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: jnlp
spec:
  containers:
    - name: jnlp
      image: s2.ubuntu.home:5000/docker.io/jenkins/inbound-agent:3283.v92c105e0f819-8-alpine-jdk21
      imagePullPolicy: Always
      resources:
        limits:
          cpu: 1
          memory: 2Gi
        requests:
          cpu: 1
          memory: 2Gi
      stdin: true
      tty: true
      volumeMounts:
        - mountPath: /home/jenkins
          name: sharedvolume
    - name: utilities
      image: s2.ubuntu.home:5000/alpine/build_container:
      command:
        - /bin/cat
      imagePullPolicy: Always
      resources:
        limits:
          cpu: 1
          memory: 2Gi
        requests:
          cpu: 1
          memory: 2Gi
      stdin: true
      tty: true
      volumeMounts:
        - mountPath: /home
          name: sharedvolume
  volumes:
    - name: sharedvolume
      emptyDir: {}
