---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: jnlp
spec:
  containers:
    - name: jnlp
      image: s2.ubuntu.home:5000/docker.io/jenkins/inbound-agent:3283.v92c105e0f819-8-alpine-jdk21
      imagePullPolicy: Always
      resources:
        limits:
          cpu: 1
          memory: 2Gi
        requests:
          cpu: 1
          memory: 2Gi
      stdin: true
      tty: true
      volumeMounts:
        - mountPath: /home/jenkins
          name: sharedvolume
    - name: builder
      image: amaas-eos-mw1.cec.lab.emc.com:5060/thirdparty/debian/uspy_template_builder:
      command:
        - /bin/cat
      imagePullPolicy: Always
      resources:
        limits:
          cpu: 1
          memory: 2Gi
        requests:
          cpu: 1
          memory: 2Gi
      stdin: true
      tty: true
      volumeMounts:
        - mountPath: /usr/local/drp/.pypirc
          name: python-pypirc
          readOnly: true
          subPath: .pypirc
        - mountPath: /home
          name: sharedvolume
  volumes:
    - name: python-pypirc
      secret:
        secretName: artifactory-access-python-secret
        items:
          - key: data
            path: .pypirc
    - name: sharedvolume
      emptyDir: {}
